# Generated by Django 5.2.7 on 2025-11-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la organización está activa y puede recibir solicitudes', verbose_name='Activa'),
        ),
    ]
