# Generated by Django 5.2.7 on 2025-11-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Dominio', 'verbose_name_plural': 'Dominios'},
        ),
    ]
