# Generated by Django 5.2.7 on 2025-11-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Resumen de Estadísticas',
                'verbose_name_plural': 'Resumen de Estadísticas',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('interview.surveysubmission',),
        ),
    ]
