# Generated by Django 5.2.7 on 2025-11-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticalsummary',
            options={'default_permissions': (), 'verbose_name': 'Resumen de Estadísticas', 'verbose_name_plural': 'Resumen de Estadísticas'},
        ),
    ]
