# Generated by Django 5.2.7 on 2026-01-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrgenerator',
            options={'default_permissions': (), 'permissions': [('can_generate_qr_codes', 'Puede generar códigos QR para unidades')], 'verbose_name': 'Generador de QR', 'verbose_name_plural': 'Generador de QR'},
        ),
    ]
