# Generated by Django 5.2.7 on 2025-10-21 21:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Respuesta de texto')),
                ('rating_answer', models.IntegerField(blank=True, null=True, verbose_name='Respuesta de calificación')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Texto de la queja')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'db_table': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Etiqueta')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Motivo de queja',
                'verbose_name_plural': 'Motivos de queja',
                'db_table': 'complaint_reasons',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('type', models.CharField(choices=[('rating', 'Calificación'), ('text', 'Texto'), ('choice', 'Opción'), ('multi_choice', 'Múltiples opciones')], default='rating', max_length=16, verbose_name='Tipo de pregunta')),
                ('position', models.IntegerField(verbose_name='Posición de la pregunta')),
                ('active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Texto de la opción')),
                ('position', models.IntegerField(verbose_name='Posición de la opción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Opción de pregunta',
                'verbose_name_plural': 'Opciones de preguntas',
                'db_table': 'question_options',
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Envío de encuesta',
                'verbose_name_plural': 'Envíos de encuestas',
                'db_table': 'survey_submissions',
            },
        ),
    ]
