# Generated by Django 5.2.7 on 2025-10-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='organization.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='organization.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='organization.unit', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='complaintreason',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_reasons', to='organization.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='interview.complaintreason', verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='question',
            name='Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='organization.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.question', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_options', to='organization.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='interview.question', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='answers', to='interview.questionoption', verbose_name='Opciones seleccionadas'),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_submissions', to='organization.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='organization.unit', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.surveysubmission', verbose_name='Envío de encuesta'),
        ),
    ]
