# Generated by Django 5.2.7 on 2025-10-25 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_answers', to='interview.questionoption', verbose_name='Opción seleccionada'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='multi_answers', to='interview.questionoption', verbose_name='Opciones seleccionadas'),
        ),
    ]
