# Generated by Django 5.2.7 on 2025-10-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_remove_surveysubmission_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='organization',
        ),
    ]
