# Generated by Django 5.2.7 on 2025-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='internal_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de interno'),
        ),
    ]
