"""
Django settings for buzon_quejas project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import sentry_sdk


from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")



# Configuración de Sentry para monitoreo de errores y rendimiento
SENTRY_DSN = os.getenv("SENTRY_DSN")
SENTRY_ENVIRONMENT = os.getenv("SENTRY_ENVIRONMENT", "development")

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Identificar el entorno (production, staging, development)
        environment=SENTRY_ENVIRONMENT,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        # Enable sending logs to Sentry
        enable_logs=True,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        # En producción considerar reducir a 0.1 (10%) para reducir costos
        traces_sample_rate=1.0 if SENTRY_ENVIRONMENT == "development" else 0.2,
        # Set profile_session_sample_rate to 1.0 to profile 100%
        # of profile sessions.
        # En producción considerar reducir a 0.1 (10%) para reducir costos
        profiles_sample_rate=1.0 if SENTRY_ENVIRONMENT == "development" else 0.2,
        # Integración con Django para capturar automáticamente errores
        integrations=[
            # Sentry SDK ya incluye integración con Django por defecto
        ],
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
os.environ.setdefault(
    "SECRET_KEY", "django-insecure-99)27wa3uc3o571$ibu^e!6#t!!xuhjry=h$3jpo6j#_a9i(^("
)
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "t")

# Configuración de ALLOWED_HOSTS para django-tenants
# Permite el dominio principal y todos sus subdominios
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.localhost',
    'tuvozenruta.com',
    '.tuvozenruta.com',
    '.up.railway.app',  # Permite subdominios en Render
]

CSRF_TRUSTED_ORIGINS = [
    'https://tuvozenruta.com',
    'https://*.tuvozenruta.com',
]

# Application definition

# 2. Define qué apps son COMPARTIDAS (esquema 'public')
# OTRA FORMA MÁS EXPLÍCITA DE ORDENAR:

# 1. Apps de tenant (incluir transport SOLO aquí)
TENANT_APPS = [
    'jazzmin',  # ← Debe ir primero para sobrescribir templates de admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django_recaptcha',  # django-recaptcha
    'apps.interview.apps.InterviewConfig',
    'apps.statistical_summary.apps.StatisticalSummaryConfig',
    'apps.transport.apps.TransportConfig',
    'apps.qr_generator.apps.QrGeneratorConfig',
    'apps.users.apps.UsersConfig',
]

# 2. Apps compartidas (transport NO va aquí)
# IMPORTANTE: Jazzmin debe ir PRIMERO, antes de django_tenants y django.contrib.admin
SHARED_APPS = [
    'jazzmin',  # ← PRIMERO para que sus templates/static tengan prioridad
    'django_tenants',
    'apps.organization.apps.OrganizationConfig',
    'apps.users.apps.UsersConfig',  # App de usuarios personalizado
    # transport NO va aquí
    'django_recaptcha',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    # Health checks - en esquema público para monitoreo general
    'health_check',
    'health_check.db',
    'health_check.contrib.migrations',
]


# 4. Construye INSTALLED_APPS de forma segura
# (Usando set para unir y luego re-ordenando)

# Esta es la forma más simple y robusta, aunque repitas un poco:
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
""" INSTALLED_APPS = [
    'django_tenants',
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tenant_manager.apps.TenantManagerConfig',
    'organization.apps.OrganizationConfig',
    'interview.apps.InterviewConfig',
    'statistical_summary.apps.StatisticalSummaryConfig',
] """


# 4. Define tu modelo Tenant
TENANT_MODEL = "organization.Organization"  # Cambiar de tenant_manager a organization
TENANT_DOMAIN_MODEL = "organization.Domain"
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True


MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",  # DEBE IR PRIMERO
    "apps.organization.middleware.TenantActiveMiddleware",  # Verificar si el tenant está activo
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "buzon_quejas.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Set default values for the environment variables if they’re not already set
os.environ.setdefault(
    "DATABASE_URL", "postgresql://buzon_user:buzon_password@localhost:5432/buzon_db"
)


# 1. Obtén la configuración de la URL de la base de datos como de costumbre
db_config = dj_database_url.config(
    default=os.environ.get("DATABASE_URL"),
    conn_max_age=600
)

# 2. ¡Importante! Sobrescribe el motor (ENGINE) por el de django-tenants
db_config['ENGINE'] = 'django_tenants.postgresql_backend'

# 3. Asigna la configuración modificada a DATABASES
DATABASES = {
    'default': db_config
}

# 6. Añade los Database Routers
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Cache Configuration (Redis)
# https://docs.djangoproject.com/en/4.2/topics/cache/

# Configuración de Redis desde variables de entorno
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Configuración de conexión
            'SOCKET_CONNECT_TIMEOUT': 5,  # segundos
            'SOCKET_TIMEOUT': 5,  # segundos
            # Compresión de datos (reduce uso de memoria)
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            # Pool de conexiones
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
        },
        'KEY_PREFIX': 'buzon_quejas',  # Prefijo para todas las claves
        'TIMEOUT': 300,  # Tiempo de expiración por defecto (5 minutos)
    }
}

# Rate Limiting Configuration (django-ratelimit)
# django-ratelimit usa automáticamente el cache 'default' configurado arriba
# Esto permite controlar el número de peticiones por IP/usuario en un tiempo determinado
RATELIMIT_ENABLE = True  # Habilitar rate limiting
RATELIMIT_USE_CACHE = 'default'  # Usar cache de Redis para almacenar contadores

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Modelo de usuario personalizado
AUTH_USER_MODEL = "users.User"

# Backend de autenticación personalizado para multi-tenancy


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Tu voz en ruta",
    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Tu voz en ruta",
    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Tu voz en ruta",
    # Logo to use for your site, must be present in static files, used for brand on top left
    # placed under interview/static/interview/images/
    "site_logo": "interview/images/logo_tu_voz_en_ruta.png",
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "interview/images/Tu_voz_en_ruta.png",
    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,
    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",
    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,
    # Welcome text on the login screen
    "welcome_sign": "Bienvenido a Tu voz en ruta",
    # Copyright on the footer
    "copyright": "C.S. code",
    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    # Dejar vacío o comentar para ocultar la barra de búsqueda del navbar
    # "search_model": ["auth.User", "auth.Group"],
    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        #{"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # Link directo al dashboard de estadísticas
        # Link directo al sitio público / aplicación (vista que muestra selección de unidad)
        {"name": "Ver encuesta", "url": "interview:select_unit", "new_window": True},
        # model admin to link to (Permissions checked against model)
        #{"model": "auth.User"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],
    #############
    # User Menu #
    #############
    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        # Enlaces duplicados para acceso móvil
    
        {"model": "auth.user"},
    ],
    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],
    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],
    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [
            {
                "name": "Make Messages",
                "url": "make_messages",
                "icon": "fas fa-comments",
                "permissions": ["books.view_book"],
            }
        ]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.user": "fas fa-user",
        # Icons for the interview app and its models
        "interview": "fas fa-poll",
        "interview.question": "fas fa-question",
        "interview.questionoption": "fas fa-list",
        # Corrected key for SurveySubmission model (was misspelled)
        "interview.surveysubmission": "fas fa-file-alt",
        "interview.answer": "fas fa-reply",
        # icons added for newly created models
        "interview.complaintreason": "fas fa-flag",
        "interview.complaint": "fas fa-exclamation-circle",
        # Organization app icons (added)
        "organization": "fas fa-building",
        "organization.organization": "fas fa-building",
        "organization.domain": "fas fa-globe",
        #transport app icons
        "transport.route": "fas fa-route",
        "transport.unit": "fas fa-bus",
        # Statistical Summary app icons
        "statistical_summary.statisticalsummary": "fas fa-chart-pie",
        # QR Generator app icons
        "qr_generator.qrgenerator": "fas fa-qrcode",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "interview/css/jazzmin_admin.css",
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    # Add a language dropdown into the admin
    "language_chooser": False,
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "es"  # traducir la interfaz administrativa al español

# Opcional: declarar idiomas soportados (útil si quieres alternar)
LANGUAGES = [
    ("es", "Español"),
    ("en", "English"),
]


# Use a valid IANA time zone name. 'UTC-7' is not a valid value for Django TIME_ZONE.
# Examples: 'UTC', 'America/Mexico_City', 'America/Los_Angeles'
TIME_ZONE = "America/Mazatlan"  # Tepic, Nayarit (UTC-7)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

PUBLIC_SCHEMA_URLCONF = 'buzon_quejas.urls_public'  # URLs para el esquema público
ROOT_URLCONF = "buzon_quejas.urls_tenant"

RECAPTCHA_PUBLIC_KEY = os.getenv("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = os.getenv("RECAPTCHA_PRIVATE_KEY")