# Generated by Django 5.2.7 on 2026-01-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticalsummary',
            options={'default_permissions': (), 'permissions': [('can_view_statistical_dashboard', 'Puede ver el dashboard de estadísticas')], 'verbose_name': 'Resumen de Estadísticas', 'verbose_name_plural': 'Resumen de Estadísticas'},
        ),
    ]
