# Generated by Django 5.2.7 on 2025-11-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0002_alter_unit_internal_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrGenerator',
            fields=[
            ],
            options={
                'verbose_name': 'Generador de QR',
                'verbose_name_plural': 'Generador de QR',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('transport.unit',),
        ),
    ]
